############################
## CHANGE THESE
############################

baseURL: 'https://dkub.dev'
title: 'Kink and Code'

############################
## MISC
############################

enableEmoji: true
# disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
enableRobotsTXT: true

markup:
  _merge: deep
