FROM hugomods/hugo:latest

COPY . /src
WORKDIR /src

RUN hugo --minify --destination /src/public

## Unnecssary when we set defaultContentLanguageInSubdir to false in hugo.toml
# RUN cp /src/public/en-us/404.html /src/public/404.html
