baseURL = '/'
defaultContentLanguage = 'en-us'
defaultContentLanguageInSubdir = true
theme = 'hermit-v2'
enableRobotsTXT = true

languageCode = 'en-us'
title = 'Kink and Code'
enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true

rssLimit = 100

copyright = "© 2024 David Kolb"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params.author]
name = "David Kolb"
about = ""
      

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  description = "A personal blog of debauchery and screaming about corporate enterprise tech."
  # images = ["author.jpg"]
  themeColor = "#494f5c"
  accentColor = "#018472"

  homeSubtitle = "Kink · Soulless Corporate Programming · Por Que Los Dos?"
  footerCopyright = "© 2024 David Kolb"
  # footerHideThemeName = false
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = false
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  # readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  # shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  descriptionInPosts = true
  tagsInPosts = true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  usesAnimation = true
  
  [[params.socialLinks]]
    name = "mastodon"
    url = "https://woof.group/@dkub"

  [[params.socialLinks]]
    name = "bluesky"
    url = "https://bsky.app/profile/dkub.dev"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/dkolb"

[menu]

  [[menu.main]]
    name = "All Posts (Includes NSFW)"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "SFW Posts Only"
    url = "tags/sfw/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 30
  
  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 40